banner:
  default:
    type: img
    bgurl: /img/banner.png
    bannerText: Hi my new friend!
  index:
    type: video
    bannerTitle: 树深时见鹿，<br>溪午不闻钟。
    bannerText: Hi my new friend!
    videoUrl: 
    bgurl: https://cdn.moji.com/websrc/video/autumn20190924.mp4
  archive:
    bannerTitle: 云间连下榻，<br>天上接行杯。
    bannerText: The article archive
  links:
    bannerTitle: 莫愁前路无知己，<br>天下谁人不识君。
    bannerText: A link to a friend's website
  comment:
    bannerTitle: 醉后不知天在水，<br>满船清梦压星河。
    bannerText: The magic tree hole
  about:
    bannerTitle: 醉后不知天在水，<br>满船清梦压星河。
    bannerText: About me
user:
  name: Trick
  first_name: blog
  last_name: Trick's
  email: 2076304828@qq.com
  domain: https://mail.qq.com/cgi-bin/frame_html?sid=MIzMmn-GdrfwOEMg&r=b376025a14dfd819f9ee0b70f1968014&lang=zh
  avatar: /img/avatar.jpg
  describe: 网站简介。
  ruleText: 暂不接受个人博客以外的友链申请，确保您的网站内容积极向上，文章至少30篇，原创70%以上，部署HTTPS。
footer:
  live_time:
    enable: true
    prefix: footer.tips
    start_time: 04/10/2022 17:00:00
toc:
  enable: true
  list_number: true
  max_depth: 3
  min_depth: 1
lazyload:
  enable: true
sidebar:
  info: # 个人信息 
    - key: 地址 
      val: wu hu       
    - key: 专业
      val: 计算机

# Think of swup as being pjax on steroids. The concepts are similar to those used in barba.js or other transition libraries.
# https://swup.js.org/
# Whether swup is enabled
swup: true
    
top_bars:
  - title: home
    url: /
    children:
  - title: archives
    url: /archives/
    noswup: false
  - title: about
    url: /about/
    noswup: false
  - title: tags
    url: /tags/
    noswup: false
  - title: categories
    url: /categories/
    noswup: false   

